spring.application.name=vivaeventos-payments
app.version=0.1.0
app.api.version=v1

server.port=8084

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vivaeventos_payments}
spring.datasource.username=${DB_USER:devdb}
spring.datasource.password=${DB_PASSWORD:a1b2c3d4}

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw}

stripe.api.key=${STRIPE_API_KEY:sk_test_51TXTrGJ2Lp92DHPeUZQVB73EFdSfoDXjtMIrToHpNESQqbZe9WYe9gO5aPdst5DTZ0Tc9Pkc7kbslyik1ELBaT8r00WDAmnfet}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_fb27781edd9ec8bf270c3664a7a4481fd6c1e36b402c16e2910600bae758c1a}

services.orders.url=${ORDERS_SERVICE_URL:http://localhost:8082}
services.tickets.url=${TICKETS_SERVICE_URL:http://localhost:8085}

payment.timeout.minutes=${PAYMENT_TIMEOUT_MINUTES:15}
payment.timeout.check.interval.ms=${PAYMENT_TIMEOUT_CHECK_INTERVAL_MS:60000}

payment.webhook.cleanup.days=${WEBHOOK_CLEANUP_DAYS:90}
payment.webhook.cleanup.cron=${WEBHOOK_CLEANUP_CRON:0 0 3 * * ?}

management.server.port=8087
